apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: "cGFzc3dvcmQ="
  mysql-database: "bGFuY2hvbmV0ZV9kYg=="
  mysql-user: "dXNlcg=="
  mysql-password: "cGFzc3dvcmQ="